name: Partial Push Hooo # Based on https://github.com/orgs/community/discussions/53762
run-name: ${{ github.actor }}'s Partial Hoooo
on: 
  push:
    branches: 
      - API-1270-git-copy-action
    paths:
      - 'api/Developers/openapi/openapi.yaml'
jobs:
  copy_openapi_file_to_openapireceive:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - run: echo "Ohh my god this is ${{ github.event_name }} event."
    - name: Check out Openapideploy project
      uses: actions/checkout@v4
    - name: Check out Openapireceive project
      uses: actions/checkout@v4
      with:
        repository: AntyAnti/openapireceive
        ref: main
        path: ./swagger/openapi.yaml
        ssh-key: ${{ secrets.TEST_KEY_FOR_RECEIVER }}
        
    - name: Copy OpenAPI file
      shell: bash
      env:
        OPENAPI_FILE: ./api/Developers/openapi/openapi.yaml
        DESTINATION_PATH: ./swagger/openapi.yaml
      run: |
        SCRIPT_NAME="$(basename "$0")"
        SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
      
        if [ -f "$OPENAPI_FILE" ]; then
          echo "Copying $OPENAPI_FILE"
          cp -R $OPENAPI_FILE $DESTINATION_PATH
          echo "OpenAPI file copied to $DESTINATION_PATH"
        else
          echo "Can't find $OPENAPI_FILE"
        fi

    - name: Push to Openapireceive repo
      shell: bash
      env:
        BRANCH: main
        
      run: |
        SCRIPT_NAME="$(basename "$0")"
        SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
        
        cd swagger/

        git ls-remote --exit-code --heads origin $BRANCH >/dev/null 2>&1
        EXIT_CODE=$?

        if [[ $EXIT_CODE == "0" ]]; then
          git fetch
          git stash
          git checkout $BRANCH
          git checkout stash -- .
        else
          git checkout -b $BRANCH
        fi

        git add -A .
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -am "feat: Update OpenAPI file replicated from CMS4"
        git push --set-upstream origin $BRANCH
