name: Partial Push Hooo # Based on https://github.com/orgs/community/discussions/53762
env:
  SOURCE_REPO: AntyAnti/openapideploy
  DESTINATION_REPO: AntyAnti/openapireceive
run-name: ${{ github.actor }}'s Partial Hoooo
on: 
  push:
    branches: 
      - master
    paths:
      - 'api/Developers/openapi/openapi.yaml'
jobs:
  copy_openapi_file_to_openapireceive:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - run: echo "Ohh my god this is ${{ github.event_name }} event."
    # check out Openapideploy project
    - name: Check out Openapideploy project
      uses: actions/checkout@v4
    # check out Openapireceive project
    - name: Check out Openapireceive project
      uses: actions/checkout@v4
      with:
        repository: AntyAnti/openapireceive
        ref: 'main'
        path: ./swagger
        ssh-key: ${{ secrets.TEST_KEY_FOR_RECEIVER }}
    # make a copy the openapi file from Openapideploy project.
    - name: Copy OpenAPI file
      run: bash ./.github/scripts/copy-openapi-yaml.sh
    # make a branch in openapireceive repo and push the copy of the openapi file there
    - name: Push to Openapireceive repo
      run: bash ./.github/scripts/push-openapi.sh
      env:
        BRANCH: main
