name: Partial Push Hooo # Based on https://github.com/orgs/community/discussions/53762
env:
  SOURCE_REPO: AntyAnti/openapideploy
  DESTINATION_REPO: AntyAnti/openapireceive
  FILES: "*.txt,LICENSE" # seperate multiple entries with ,
  AUTOMATIC_MONITOR: true
run-name: ${{ github.actor }}'s Partial Hoooo
on: 
  push:
    branches: 
      - master
    paths:
      - 'api/Developers/openapi/openapi.yaml'
jobs:
  copy_openapi_file_to_openapireceive:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Ohh my god this is ${{ github.event_name }} event."
    # check out notehub project
    - name: Check out Openapideploy project
      uses: actions/checkout@v3
    # check out Openapireceive project
    - name: Check out Openapireceive JS project
      uses: actions/checkout@v3
      with:
        repository: AntyAnti/openapireceive
        path: ./openapireceive
    # make a copy the openapi file from Openapideploy project.
    - name: Copy OpenAPI file
      run: bash ./.github/scripts/copy-openapi-yaml.sh
      env:
        DESTINATION_PATH: ./openapireceive/
